import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const browser = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox"] });
const p = await browser.newPage();
await p.setViewport({ width: 1280, height: 620, deviceScaleFactor: 1.5 });
await p.setCookie({ name: "flow_session", value: "u-barbero-demo", domain: "localhost", path: "/" });
await p.goto("http://localhost:3000/panel/turnos", { waitUntil: "networkidle0", timeout: 60000 });
await new Promise((r) => setTimeout(r, 700));
await p.screenshot({ path: "/tmp/aligned.png" });
await browser.close(); console.log("done");
